#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/yaakov/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/yaakov/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/yaakov/NEUR634/CA1_Project/Attenuation/Simulate Figures 3-5/Ri04_Figs3-5/x86_64/.libs/libnrnmech.so" "$@"
